// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mldpqoezymxtlxjrwybp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sZHBxb2V6eW14dGx4anJ3eWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MjM0NTksImV4cCI6MjA2MjQ5OTQ1OX0.Ut-Jj2oln4xxdWk9hsF3BF6Ngzo8Qu8wXuWWBPgrisE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);